channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.17
  - pip:
      - azureml-train-automl-runtime==1.52.0
      - inference-schema
      - azureml-interpret==1.52.0
      - azureml-defaults==1.52.0
  - numpy==1.22.3
  - pandas==1.1.5
  - scikit-learn==0.22.1
  - py-xgboost==1.3.3
  - fbprophet==0.7.1
  - holidays==0.10.3
  - psutil==5.9.5
name: project_environment
